baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Aditya Nawandhar'
theme = "paper"
relativeURLs = true
canonifyURLs = true

[params]
  name = 'Aditya Nawandhar'
  bio = 'Software Engineer & Tech Enthusiast'
  avatar = 'images/Aditya-Nawandhar.jpg'

[menu]

  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/post/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10